config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'

  resources :todos, only: [:index, :new, :create]
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path
    else
      render :new
    end
  end

  private

    def todo_params
      params.require(:todo).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todos
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %h1= "Welcome to todos"
    = yield

app/views/todos/index.html.haml
= link_to "New todo", new_todo_path

- @todos.each do |todo|
  %ul{ class: "todos" }
    %li= todo.name

app/views/todos/new.html.haml
= form_for @todo do |f|
  - if @todo.errors.any?
    %h2 Errors:
    - @todo.errors.full_messages.each do |message|
      %ul{class: "errors"}
        %li= message
  = f.label :name
  = f.text_field :name
  = f.submit "Add"